name: Update boostlook.css in website-v2

on:
  push:
    branches: [ "master" ]
    paths:
      - 'boostlook.css'

jobs:
  update-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout boostlook repository
        uses: actions/checkout@v3

      - name: Checkout website-v2 repository
        uses: actions/checkout@v3
        with:
          repository: boostorg/website-v2
          ref: develop
          path: website-v2
          token: ${{ secrets.WEBSITE_V2_PAT }}

      - name: Copy boostlook.css to website-v2
        run: |
          cp boostlook.css website-v2/static/css/boostlook.css

      - name: Commit and push changes
        working-directory: website-v2
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add static/css/boostlook.css
          git commit -m "Update boostlook.css from boostlook repository"
          git push origin develop